### ISSUE TITLE
Releases RoadMap

### ISSUE THREAD

**Issue by UlisesGascon** [memezinga/memegeddon#3]
### v1.0.1
- [x] Mejorar Documentación
- [x] Implementar Tests

### v1.1.0
- [x] Migrar a Firestore

### v1.2.0
- [ ] Procesar la imagen en Google Vision API usando [la librería @google-cloud/vision](https://www.npmjs.com/package/@google-cloud/vision)
    - [ ] [`detectSafeSearch`](https://github.com/googleapis/nodejs-vision/blob/master/samples/detect.js#L287) para saber si la imagen contiene contenido explícito
    - [ ] [`detectProperties `](https://github.com/googleapis/nodejs-vision/blob/master/samples/detect.js#L245) para obtener los colores predominantes
- [ ] Usaremos  la librería [`tinyPng`](https://www.npmjs.com/package/tinify) para comprimir las imágenes y generar los thumbs
- [ ] Validación de concidéncias con los memes almacenados usando campos de texto y valores hash de las imágenes
- [ ] Implementar un sistema de Cron-jobs
